package io.everytrade.server.plugin.impl.everytrade.parser.exchange.binance.v4;

public enum BinanceOperationTypeV4 {
    // Supported account types
    ACCOUNT_TYPE_SPOT("SPOT", true),
    ACCOUNT_TYPE_CARD("CARD", true),
    ACCOUNT_TYPE_EARN("EARN", true),
    // UNSUPPORTED ACCOUNT TYPES
    ACCOUNT_TYPE_CROSS_MARGIN("CROSSMARGIN", true),
    ACCOUNT_TYPE_ISOLATED_MARGIN("ISOLATEDMARGIN", true),
    ACCOUNT_TYPE_P2P("P2P", true),
    ACCOUNT_TYPE_POOL("POOL", true),
    ACCOUNT_TYPE_USDT_FUTURES("USDT-FUTURES", true),

    // SUPPORTED OPERATIONS
    OPERATION_TYPE_BUY("BUY", true),
    OPERATION_TYPE_SELL("SELL", true),
    OPERATION_TYPE_WITHDRAWAL("WITHDRAW", true),
    OPERATION_TYPE_DEPOSIT("DEPOSIT", true),
    OPERATION_TYPE_TRANSACTION_RELATED("TRANSACTION RELATED", true),
    OPERATION_TYPE_FEE("FEE", true),
    OPERATION_TYPE_DISTRIBUTION("DISTRIBUTION", true),
    OPERATION_TYPE_FIAT_WITHDRAWAL("FIAT WITHDRAWAL", true),
    OPERATION_TYPE_FIAT_DEPOSIT("FIAT DEPOSIT", true),
    OPERATION_TYPE_CARD_CASHBACK("CARD CASHBACK", false),
    OPERATION_TYPE_COMMISSION_REBATE("COMMISSION REBATE", false),
    OPERATION_TYPE_SMALL_ASSETS_EXCHANGE_BNB("SMALL ASSETS EXCHANGE BNB", true),
    OPERATION_TYPE_SIMPLE_EARN_FLEXIBLE_INTEREST("SIMPLE EARN FLEXIBLE INTEREST", false),
    OPERATION_TYPE_BINANCE_CONVERT("BINANCE CONVERT", true),
    OPERATION_TYPE_TRANSACTION_BUY("TRANSACTION BUY", true),
    OPERATION_TYPE_TRANSACTION_SPEND("TRANSACTION SPEND", true),
    OPERATION_TYPE_TRANSACTION_REVENUE("TRANSACTION REVENUE", true),
    OPERATION_TYPE_TRANSACTION_SOLD("TRANSACTION SOLD", true),
    OPERATION_TYPE_BUY_CRYPTO("BUY CRYPTO", true),

    // UNSUPPORTED OPERATIONS
    OPERATION_TYPE_MARGIN_LOAN("MARGIN LOAN", true),
    OPERATION_TYPE_MARGIN_REPAYMENT("MARGIN REPAYMENT", true),
    OPERATION_TYPE_BNB_DEDUCT_FEE("BNB DEDUCTS FEE", true),
    OPERATION_TYPE_ISOLATED_MARGIN_LOAN("ISOLATEDMARGIN LOAN", true),
    OPERATION_TYPE_ISOLATED_MARGIN_REPAYMENT("ISOLATEDMARGIN REPAYMENT", true),
    OPERATION_TYPE_TRANSFER_IN("TRANSFER_IN", true),
    OPERATION_TYPE_TRANSFER_OUT("TRANSFER_OUT", true),
    OPERATION_TYPE_P2P_TRADING("P2P TRADING", true),
    OPERATION_TYPE_POOL_DISTRIBUTION("POOL DISTRIBUTION", true),
    OPERATION_TYPE_BNB_DEDUCTS_FEE("BNB DEDUCTS FEE", true),
    OPERATION_TYPE_COMMISSION_FEE_SHARED_WITH_YOU("COMMISSION FEE SHARED WITH YOU", true),
    OPERATION_TYPE_COMMISSION_HISTORY("COMMISSION HISTORY", true),
    OPERATION_TYPE_LARGE_OTC_TRADING("LARGE OTC TRADING", true),
    OPERATION_TYPE_LAUNCHPOOL_INTEREST("LAUNCHPOOL INTEREST", true),
    OPERATION_TYPE_LIQUID_SWAP_ADD("LIQUID SWAP ADD", true),
    OPERATION_TYPE_POS_SAVINGS_INTEREST("POS SAVINGS INTEREST", true),
    OPERATION_TYPE_POS_SAVINGS_PURCHASE("POS SAVINGS PURCHASE", true),
    OPERATION_TYPE_POS_SAVINGS_REDEMPTION("POS SAVINGS REDEMPTION", true),
    OPERATION_TYPE_SAVINGS_INTEREST("SAVINGS INTEREST", true),
    OPERATION_TYPE_SAVINGS_PRINCIPAL_REDEMPTION("SAVINGS PRINCIPAL REDEMPTION", true),
    OPERATION_TYPE_SAVINGS_PURCHASE("SAVINGS PURCHASE", true),
    OPERATION_TYPE_SMALL_ASSET_EXCHANGE_BNB("SMALL ASSETS EXCHANGE BNB", true),
    OPERATION_TYPE_SUPER_BNB_MINING("SUPER BNB MINING", true),
    OPERATION_TYPE_FUNDING_FEE("FUNDING FEE", true),
    OPERATION_TYPE_INSURANCE_FUND_COMPENSATION("INSURANCE FUND COMPENSATION", true),
    OPERATION_TYPE_REALIZE_PROFIT_AND_LOSS("REALIZE PROFIT AND LOSS", true),
    OPERATION_TYPE_REFEREE_REBATES("REFEREE REBATES", true),

    //REMARKS
    REMARKS_NO_FEE("WITHDRAW FEE IS INCLUDED", true);

    public final String code;
    public final boolean isMultiRowType;

    BinanceOperationTypeV4(String code, boolean isMultiRowType) {
        this.code = code;
        this.isMultiRowType = isMultiRowType;
    }

    public static BinanceOperationTypeV4 getEnum(String name) {
        for (BinanceOperationTypeV4 e : values()) {
            if (e.code.equalsIgnoreCase(name)) {
                return e;
            }
        }
        return null;
    }

}
